name: pOmniTagger
channels:
  - conda-forge
  - nodefaults

dependencies:
  - python >=3.10, <3.11
  - ipython
  - pip
  - pip:
    - flask
    - pandas
    - requests
    - opencv-python
    - pyside6
    - QtPy
    - pywebview[pyside6]
    - pythonnet



