name: pOmniTagger
channels:
  - conda-forge
  - nodefaults

dependencies:
  - python >=3.10, <3.11
  - ipython
  - pip
  - pip:
    - dash
    - dash_dangerously_set_inner_html
    - flask
    - pandas
    - requests
    - opencv-python
    - pywebview
#    - PySide2
#    - pythonnet
#    - QtPy


