name: pOmniTagger
channels:
  - conda-forge
  - nodefaults

dependencies:
  - python >=3.10, <3.11
  - ipython
  - pip
  - pip:
    - dash
    - pandas
    - requests
    - opencv-python
    - pywebview


